AWSTemplateFormatVersion: 2010-09-09

Resources:
  # =-=: S3 :=-= #
  InvestAppWebsiteS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: invest-app-website
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    # DeletionPolicy: Retain # CloudFormation will not delete this bucket when it deletes the stack

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: InvestAppWebsitePolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref InvestAppWebsiteS3Bucket
                - /*
            Condition:
              IpAddress:
                aws:SourceIp:
                  - '177.132.65.163/24'
                  - '189.16.40.2/32'
      Bucket: !Ref InvestAppWebsiteS3Bucket

Outputs:
  InvestAppWebsiteURL:
    Value: !GetAtt 
      - InvestAppWebsiteS3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3
  InvestAppWebsiteS3Bucket:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - InvestAppWebsiteS3Bucket
          - DomainName
    Description: Name of S3 bucket to hold website content