AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  invest-app

  Sample SAM Template for invest-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  Stage:
    Type: String
  Version:
    Type: String

Resources:
  # =-=: API :=-= #
  InvestCrudAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: AWS_IAM

  # =-=: LAMBDA :=-= #
  StockListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-all-items.getAllItems
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref InvestmentTable
      Environment:
        Variables:
          INVESTMENT_TABLE_NAME: !Ref InvestmentTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref InvestCrudAPI
            Path: /
            Method: GET

  StockGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-by-id.getById
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref InvestmentTable
      Environment:
        Variables:
          INVESTMENT_TABLE_NAME: !Ref InvestmentTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref InvestCrudAPI
            Path: /{id}
            Method: GET

  StockCreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/save-item.create
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref InvestmentTable
      Environment:
        Variables:
          INVESTMENT_TABLE_NAME: !Ref InvestmentTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref InvestCrudAPI
            Path: /
            Method: POST

  StockUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/save-item.update
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref InvestmentTable
      Environment:
        Variables:
          INVESTMENT_TABLE_NAME: !Ref InvestmentTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref InvestCrudAPI
            Path: /{id}
            Method: PUT

  StockDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/delete-item.deleteById
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref InvestmentTable
      Environment:
        Variables:
          INVESTMENT_TABLE_NAME: !Ref InvestmentTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref InvestCrudAPI
            Path: /{id}
            Method: DELETE

  # =-=: Dynamo :=-= #
  InvestmentTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${InvestCrudAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
